services:
    mock-tplink-api:
      image: wiremock/wiremock:2.35.1-1
      restart: always
      ports:
        # HTTP
        - "8080:8080" 
        # HTTPS
        # - "8443:8443"
      volumes:
        - ./tests/wiremock:/home/wiremock
